### PR TITLE
Fix issues with setting publish directory

### PR DESCRIPTION
**Pull request by MineRobber9000**
Paging @modgethanc because this is important.

### CODE REVIEW

**Comment by modgethanc** [comment]
I think your bug was with the version updater, not with the publish directory setting; I can't replicate your bug using the current version (0.9.1). So, this pull request doesn't actually address that problem, but thanks for calling my attention to it! I'm looking into the version updater to try and track this down.

**Comment by MineRobber9000** [comment]
OK. I might submit another pull to fix the symptom of the issue (publishing not working since the publish directory gets nuked when the updater goes through, it seems.)

**Comment by modgethanc** [comment]
[This commit](https://github.com/modgethanc/ttbp/commit/aebdd51d08fa306fe3bb4f17b9e546d720dcef8a) should fix it, but it'll be hard to tell if it worked until someone updates from <0.8.6

**Comment by MineRobber9000** [comment]
alright. My idea was to add a small menu to the main menu if the updater deleted your publish directory, and had you change it.

**Pull request closed without merging**
